In [1]:
# import all required packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# read the data
df = pd.read_csv('Wine.csv')
# print(df.head())
# print(len(df.columns))

In [3]:
# decide x and y
x = df.drop('Customer_Segment', axis=1)
y = df['Customer_Segment']

In [4]:
# split the data into train and test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)

### QDA

In [11]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

qda = QuadraticDiscriminantAnalysis()

# extract features from train
a = qda.fit(x_train, y_train).predict(x_test)
print(x_test)
print(a)

     Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
172    14.16        2.51  2.48          20.0         91           1.68   
24     13.50        1.81  2.61          20.0         96           2.53   
145    13.16        3.57  2.15          21.0        102           1.50   
156    13.84        4.12  2.38          19.5         89           1.80   
90     12.08        1.83  2.32          18.5         81           1.60   
117    12.42        1.61  2.19          22.5        108           2.00   
137    12.53        5.51  2.64          25.0         96           1.79   
83     13.05        3.86  2.32          22.5         85           1.65   
148    13.32        3.24  2.38          21.5         92           1.93   
112    11.76        2.68  2.92          20.0        103           1.75   
76     13.03        0.90  1.71          16.0         86           1.95   
105    12.42        2.55  2.27          22.0         90           1.68   
171    12.77        2.39  2.28        

### data cleansing process

In [13]:
# look out the missing data
# use the correct data type
# add new columns if needed
# drop existing columns if needed

# scale the features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# scale the x_train features
x_train = scaler.fit_transform(x_train)

# scale the x_test features
x_test = scaler.fit_transform(x_test)

### Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegressionCV

# create a model
model = LogisticRegressionCV(max_iter=1000)

# train the model
model.fit(x_train, y_train)

# predict the values from x_test
y_prediction = model.predict(x_test)

# evaluation
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

print(confusion_matrix(y_test, y_prediction))

[[11  0  0]
 [ 0 13  1]
 [ 0  0 11]]


In [15]:
print(classification_report(y_test, y_prediction))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       1.00      0.93      0.96        14
           3       0.92      1.00      0.96        11

    accuracy                           0.97        36
   macro avg       0.97      0.98      0.97        36
weighted avg       0.97      0.97      0.97        36



In [16]:
print(accuracy_score(y_test, y_prediction))

0.9722222222222222
